import { AlertTriangle, CarFront, Check, Clipboard, Database, Download, Gauge, History, Leaf, Store } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { useEffect, useState } from 'react';
import { createAiPrompt, downloadChecklist } from '../analysis/export';
import { getRegistrationTaxBand } from '../analysis/registration-tax';
import type { ListingAnalysis } from '../shared/messages';
import type { ExtractedField } from '../shared/listing';
import './styles.css';

const show = <T,>(field: ExtractedField<T> | undefined, format: (value: T) => string = String): string => field?.value === undefined ? 'Desconocido' : format(field.value);
function DataRow({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[minmax(7rem,0.8fr)_1.2fr] gap-2 border-b border-slate-200 py-1.5"><dt className="text-slate-500">{label}</dt><dd className="m-0 break-words font-medium">{value}</dd></div>; }
function EmissionsRow({ co2Gkm }: { co2Gkm?: number }) { const band = co2Gkm === undefined ? undefined : getRegistrationTaxBand(co2Gkm); return <div className="grid grid-cols-[minmax(7rem,0.8fr)_1.2fr] gap-2 border-b border-slate-200 py-1.5"><dt className="text-slate-500">CO₂ e impuesto</dt><dd className={`m-0 break-words font-semibold ${band?.colorClass ?? 'text-slate-500'}`}>{band ? `${co2Gkm} g/km · ${String(band.rate).replace('.', ',')}%` : 'Desconocido'}</dd></div>; }
function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><h2 className="mb-2 flex items-center gap-2 font-semibold">{icon}{title}</h2>{children}</section>; }

function SidePanel() {
  const [analysis, setAnalysis] = useState<ListingAnalysis>(); const [error, setError] = useState(false); const [copied, setCopied] = useState(false); const [generatingChecklist, setGeneratingChecklist] = useState(false);
  useEffect(() => {
    const load = () => chrome.runtime.sendMessage({ type: 'get-last-analysis' }).then((result: unknown) => { if (result && typeof result === 'object' && 'listing' in result) setAnalysis(result as ListingAnalysis); }).catch(() => setError(true));
    const changed = (changes: Record<string, chrome.storage.StorageChange>) => { if (changes.lastAnalysisUpdated) load(); };
    load(); chrome.storage.onChanged.addListener(changed); return () => chrome.storage.onChanged.removeListener(changed);
  }, []);
  const listing = analysis?.listing; const engine = analysis?.engineAnalysis?.motor_detectado;
  const copyPrompt = async () => { if (!analysis) return; try { await navigator.clipboard.writeText(createAiPrompt(analysis)); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setError(true); } };
  const createChecklist = async () => { if (!analysis || generatingChecklist) return; setGeneratingChecklist(true); try { await downloadChecklist(analysis); } catch { setError(true); } finally { setGeneratingChecklist(false); } };
  if (error) return <main className="p-4"><p role="alert" className="text-sm text-red-700">No se pudo leer o copiar el análisis local. Recarga la extensión y el anuncio.</p></main>;
  return <main className="min-h-screen bg-slate-50 p-3 text-sm"><header className="mb-3 flex items-center gap-2"><CarFront aria-hidden="true" /><div><h1 className="text-lg font-bold">Import Analyzer</h1><p className="text-xs text-slate-500">Análisis local, no sustituye una inspección</p></div></header>{!analysis || !listing ? <p className="rounded-xl bg-white p-4 text-slate-600">Esperando un anuncio de Mobile.de. Abre una ficha de vehículo y mantén este panel visible.</p> : <div className="space-y-3"><section className="rounded-xl bg-slate-900 p-4 text-white"><h2 className="text-base font-semibold">{listing.title?.value ?? 'Vehículo sin título'}</h2><p className="mt-1 text-slate-300">{show(listing.grossPrice, (price) => `${(price.amountMinor / 100).toLocaleString('es-ES')} ${price.currency}`)} · {show(listing.mileageKm, (km) => `${km.toLocaleString('es-ES')} km`)}</p><p className="mt-2 break-all text-xs text-slate-400">ID {listing.listingId?.value ?? 'desconocido'}</p></section>
  <Section title="Mecánica" icon={<Gauge size={16} />}><dl><DataRow label="Potencia" value={`${show(listing.powerKw, (v) => `${v} kW`)} / ${show(listing.powerCv, (v) => `${v} CV`)}`} /><DataRow label="Cilindrada" value={show(listing.displacementCc, (v) => `${v} cc`)} /><DataRow label="Combustible" value={show(listing.fuel)} /><DataRow label="Transmisión" value={show(listing.transmission)} /><DataRow label="Cilindros" value={show(listing.cylinders)} /><DataRow label="Depósito" value={show(listing.tankLitres, (v) => `${v} l`)} /></dl><div className="mt-3 rounded-lg bg-slate-100 p-2"><strong>Motor probable:</strong> {engine ? `${engine.codigo_motor} · ${engine.familia}` : 'No identificado con evidencia suficiente'}<p className="mt-1 text-xs text-slate-600">{engine ? `${engine.nivel_identificacion} · ${engine.confianza} (${engine.puntuacion}/100), sin confirmar` : analysis.engineAnalysis?.motivo_coincidencia[0] ?? 'No se inventa un código cuando faltan coincidencias.'}</p>{engine?.motivo_coincidencia.map((reason) => <p className="mt-1 text-xs text-slate-600" key={reason}>{reason}</p>)}</div></Section>
  <Section title="Historial" icon={<History size={16} />}><dl><DataRow label="Marca/modelo" value={`${show(listing.make)} ${show(listing.model)}`} /><DataRow label="Versión" value={show(listing.variant)} /><DataRow label="Primera matriculación" value={show(listing.firstRegistration, ({ year, month }) => `${month ? String(month).padStart(2, '0') + '/' : ''}${year}`)} /><DataRow label="Propietarios" value={show(listing.owners)} /><DataRow label="Generación" value={show(listing.modelRange)} /><DataRow label="Acabado" value={show(listing.trim)} /></dl></Section>
  <Section title="Equipamiento" icon={<Check size={16} />}>{Object.keys(listing.features).length ? Object.entries(listing.features).map(([group, feature]) => <div className="mb-2" key={group}><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">{group.replace('seller:', 'Descripción: ')}</h3><p className="mt-1 leading-5">{feature.value?.join(' · ')}</p></div>) : <p className="text-slate-500">No se pudieron extraer extras.</p>}<details className="mt-3"><summary className="cursor-pointer font-medium">Descripción original del vendedor</summary><p className="mt-2 whitespace-pre-line text-xs leading-5 text-slate-600">{listing.description?.value ?? 'No extraída'}</p></details></Section>
  <Section title="Emisiones" icon={<Leaf size={16} />}><dl><EmissionsRow co2Gkm={listing.co2Gkm?.value} /><DataRow label="Clase" value={show(listing.emissionClass)} /><DataRow label="Puertas" value={show(listing.doors)} /></dl></Section>
  <Section title="Vendedor" icon={<Store size={16} />}><dl><DataRow label="Nombre" value={listing.seller?.value?.name ?? 'Desconocido'} /><DataRow label="Tipo" value={listing.seller?.value?.type ?? 'Desconocido'} /><DataRow label="País" value={listing.seller?.value?.country ?? 'Desconocido'} /></dl></Section>
  <Section title="Riesgos y contradicciones" icon={<AlertTriangle size={16} />}>{analysis.flags.length ? analysis.flags.map((flag, index) => <article className="mb-2 border-l-2 border-amber-500 pl-2" key={`${flag.category}-${index}`}><strong>{flag.severity.toUpperCase()} · {flag.category}</strong><p className="text-slate-600">“{flag.excerpt}”</p></article>) : <p className="text-slate-500">No se detectaron frases de alerta con las reglas actuales; no equivale a ausencia de riesgos.</p>}{listing.extractionLog.length ? <p className="mt-2 text-xs text-amber-700">Campos no extraídos: {listing.extractionLog.map((entry) => entry.replace('missing:', '')).join(', ')}</p> : null}</Section>
  <div className="sticky bottom-0 grid grid-cols-2 gap-2 bg-slate-50 py-2"><button className="inline-flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-3 py-2.5 font-medium text-white" onClick={copyPrompt}>{copied ? <Check size={16} /> : <Clipboard size={16} />}{copied ? 'Copiado' : 'Prompt IA'}</button><button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-400 bg-white px-3 py-2.5 font-medium disabled:cursor-wait disabled:opacity-60" disabled={generatingChecklist} onClick={() => void createChecklist()}><Download size={16} />{generatingChecklist ? 'Generando…' : 'Checklist'}</button></div><p className="flex items-center gap-1 text-xs text-slate-500"><Database size={14} />Guardado localmente · {new Date(analysis.savedAt).toLocaleString('es-ES')}</p></div>}</main>;
}

createRoot(document.getElementById('root')!).render(<SidePanel />);
